<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(AppMonoGameTargetFramework)</TargetFramework>
    <AssemblyName>Nursia.Samples.Character</AssemblyName>
    <RootNamespace>Nursia.Samples.Character</RootNamespace>
    <OutputPath>bin\MonoGame.DesktopGL\$(Configuration)</OutputPath>
    <DefineConstants>$(DefineConstants);MONOGAME</DefineConstants>
  </PropertyGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Effects\MonoGameOGL\bin\ReflectionPlane.efb" />
  </ItemGroup>  

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="$(AppMonoGameVersion)" />
    <PackageReference Include="Myra" Version="$(MyraVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Nursia\Nursia.MonoGame.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
