<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(FNATargetFramework)</TargetFramework>
    <RootNamespace>Nursia.Samples.ThirdPerson</RootNamespace>
    <DefineConstants>$(DefineConstants);FNA</DefineConstants>
    <OutputPath>bin\FNA.Core\$(Configuration)</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Effects\FNA\bin\ReflectionPlane.efb" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Effects\FNA\bin\ReflectionPlane.efb" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Nursia\Nursia.FNA.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>  

</Project>
