/* Generated by MyraPad at 11/23/2025 7:33:12 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Nursia.Editor.UI
{
	partial class AddNewSceneNodeDialog: Dialog
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "File Name:";

			_textName = new TextBox();
			_textName.Id = "_textName";
			StackPanel.SetProportionType(_textName, Myra.Graphics2D.UI.ProportionType.Fill);

			_panelFilename = new HorizontalStackPanel();
			_panelFilename.Spacing = 8;
			_panelFilename.Id = "_panelFilename";
			_panelFilename.Widgets.Add(label1);
			_panelFilename.Widgets.Add(_textName);

			_panelNodes = new ScrollViewer();
			_panelNodes.ScrollMultiplier = 10;
			_panelNodes.Id = "_panelNodes";
			StackPanel.SetProportionType(_panelNodes, Myra.Graphics2D.UI.ProportionType.Fill);

			var label2 = new Label();
			label2.Text = "Filter:";

			_textFilter = new TextBox();
			_textFilter.Id = "_textFilter";
			StackPanel.SetProportionType(_textFilter, Myra.Graphics2D.UI.ProportionType.Fill);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(label2);
			horizontalStackPanel1.Widgets.Add(_textFilter);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(_panelFilename);
			verticalStackPanel1.Widgets.Add(_panelNodes);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);

			
			Title = "Add New Scene Node";
			Left = 514;
			Top = 128;
			Width = 500;
			Height = 400;
			Content = verticalStackPanel1;
		}

		
		public TextBox _textName;
		public HorizontalStackPanel _panelFilename;
		public ScrollViewer _panelNodes;
		public TextBox _textFilter;
	}
}
