/* Generated by MyraPad at 10/30/2025 5:26:28 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Nursia.Editor.UI
{
	partial class CreateNewTerrainDialog: Dialog
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "SplatMap Size:";

			var label2 = new Label();
			label2.Text = "256x256";

			var label3 = new Label();
			label3.Text = "512x512";

			var label4 = new Label();
			label4.Text = "1024x1024";

			_comboSplatMapSize = new ComboView();
			_comboSplatMapSize.Id = "_comboSplatMapSize";
			Grid.SetColumn(_comboSplatMapSize, 1);
			_comboSplatMapSize.Widgets.Add(label2);
			_comboSplatMapSize.Widgets.Add(label3);
			_comboSplatMapSize.Widgets.Add(label4);

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.DefaultColumnProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.Widgets.Add(label1);
			grid1.Widgets.Add(_comboSplatMapSize);

			
			Title = "Create New Terrain";
			Left = 636;
			Top = 341;
			Content = grid1;
		}

		
		public ComboView _comboSplatMapSize;
	}
}
