/* Generated by MyraPad at 5/24/2026 1:25:15 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Nursia.Editor.UI
{
	partial class MainForm: VerticalStackPanel
	{
		private void BuildUI()
		{
			_menuItemSaveCurrentItem = new MenuItem();
			_menuItemSaveCurrentItem.Text = "&Save Current Item";
			_menuItemSaveCurrentItem.Id = "_menuItemSaveCurrentItem";

			_menuItemSaveEverything = new MenuItem();
			_menuItemSaveEverything.Text = "Save &Everything";
			_menuItemSaveEverything.Id = "_menuItemSaveEverything";

			_menuItemReloadCurrentItem = new MenuItem();
			_menuItemReloadCurrentItem.Text = "&Reload Current Item";
			_menuItemReloadCurrentItem.Id = "_menuItemReloadCurrentItem";

			_menuItemProjectReferences = new MenuItem();
			_menuItemProjectReferences.Text = "&Project References";
			_menuItemProjectReferences.Id = "_menuItemProjectReferences";

			_menuItemQuit = new MenuItem();
			_menuItemQuit.Text = "&Quit";
			_menuItemQuit.Id = "_menuItemQuit";

			var menuItem1 = new MenuItem();
			menuItem1.Text = "&File";
			menuItem1.Items.Add(_menuItemSaveCurrentItem);
			menuItem1.Items.Add(_menuItemSaveEverything);
			menuItem1.Items.Add(_menuItemReloadCurrentItem);
			menuItem1.Items.Add(_menuItemProjectReferences);
			menuItem1.Items.Add(_menuItemQuit);

			_menuItemGraphicsSettings = new MenuItem();
			_menuItemGraphicsSettings.Text = "&Graphics Settings";
			_menuItemGraphicsSettings.Id = "_menuItemGraphicsSettings";

			_menuItemRenderEnvironment = new MenuItem();
			_menuItemRenderEnvironment.Text = "&Render Environment";
			_menuItemRenderEnvironment.Id = "_menuItemRenderEnvironment";

			_menuItemDebugSettings = new MenuItem();
			_menuItemDebugSettings.Text = "&Debug Settings";
			_menuItemDebugSettings.Id = "_menuItemDebugSettings";

			var menuItem2 = new MenuItem();
			menuItem2.Text = "&Options";
			menuItem2.Items.Add(_menuItemGraphicsSettings);
			menuItem2.Items.Add(_menuItemRenderEnvironment);
			menuItem2.Items.Add(_menuItemDebugSettings);

			_menuItemAbout = new MenuItem();
			_menuItemAbout.Text = "&About";
			_menuItemAbout.Id = "_menuItemAbout";

			var menuItem3 = new MenuItem();
			menuItem3.Text = "&Help";
			menuItem3.Items.Add(_menuItemAbout);

			var horizontalMenu1 = new HorizontalMenu();
			horizontalMenu1.Items.Add(menuItem1);
			horizontalMenu1.Items.Add(menuItem2);
			horizontalMenu1.Items.Add(menuItem3);

			_panelSceneExplorer = new ScrollViewer();
			_panelSceneExplorer.Id = "_panelSceneExplorer";

			_panelSolution = new ScrollViewer();
			_panelSolution.Id = "_panelSolution";

			_leftSplitPane = new VerticalSplitPane();
			_leftSplitPane.Id = "_leftSplitPane";
			_leftSplitPane.Widgets.Add(_panelSceneExplorer);
			_leftSplitPane.Widgets.Add(_panelSolution);

			var label1 = new Label();
			label1.Text = "Grid";

			_buttonGrid = new ToggleButton();
			_buttonGrid.Id = "_buttonGrid";
			_buttonGrid.Content = label1;

			var label2 = new Label();
			label2.Text = "Camera Position";

			_buttonCameraPosition = new ToggleButton();
			_buttonCameraPosition.Id = "_buttonCameraPosition";
			_buttonCameraPosition.Content = label2;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_buttonGrid);
			horizontalStackPanel1.Widgets.Add(_buttonCameraPosition);

			var label3 = new Label();
			label3.Text = "Camera View";

			var toggleButton1 = new ToggleButton();
			toggleButton1.Content = label3;

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Left = 2;
			horizontalStackPanel2.Top = 2;
			horizontalStackPanel2.Widgets.Add(toggleButton1);

			var tabItem1 = new TabItem();
			tabItem1.Text = "Test";
			tabItem1.Content = horizontalStackPanel2;

			_tabControlScenes = new TabControl();
			_tabControlScenes.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_tabControlScenes.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_tabControlScenes.CloseableTabs = true;
			_tabControlScenes.Id = "_tabControlScenes";
			_tabControlScenes.Items.Add(tabItem1);

			var label4 = new Label();
			label4.Text = "FPS:";

			var label5 = new Label();
			label5.Text = "Effects Switches:";
			Grid.SetRow(label5, 1);

			var label6 = new Label();
			label6.Text = "Draw Calls:";
			Grid.SetRow(label6, 2);

			var label7 = new Label();
			label7.Text = "Vertices Drawn:";
			Grid.SetRow(label7, 3);

			var label8 = new Label();
			label8.Text = "Primitives Drawn:";
			Grid.SetRow(label8, 4);

			var label9 = new Label();
			label9.Text = "Passes:";
			Grid.SetRow(label9, 5);

			_labelFps = new Label();
			_labelFps.Text = "10";
			_labelFps.Id = "_labelFps";
			Grid.SetColumn(_labelFps, 1);

			_labelEffectsSwitches = new Label();
			_labelEffectsSwitches.Text = "10";
			_labelEffectsSwitches.Id = "_labelEffectsSwitches";
			Grid.SetColumn(_labelEffectsSwitches, 1);
			Grid.SetRow(_labelEffectsSwitches, 1);

			_labelDrawCalls = new Label();
			_labelDrawCalls.Text = "10";
			_labelDrawCalls.Id = "_labelDrawCalls";
			Grid.SetColumn(_labelDrawCalls, 1);
			Grid.SetRow(_labelDrawCalls, 2);

			_labelVerticesDrawn = new Label();
			_labelVerticesDrawn.Text = "10";
			_labelVerticesDrawn.Id = "_labelVerticesDrawn";
			Grid.SetColumn(_labelVerticesDrawn, 1);
			Grid.SetRow(_labelVerticesDrawn, 3);

			_labelPrimitivesDrawn = new Label();
			_labelPrimitivesDrawn.Text = "10";
			_labelPrimitivesDrawn.Id = "_labelPrimitivesDrawn";
			Grid.SetColumn(_labelPrimitivesDrawn, 1);
			Grid.SetRow(_labelPrimitivesDrawn, 4);

			_labelPasses = new Label();
			_labelPasses.Text = "10";
			_labelPasses.Id = "_labelPasses";
			Grid.SetColumn(_labelPasses, 1);
			Grid.SetRow(_labelPasses, 5);

			_panelStatistics = new Grid();
			_panelStatistics.ColumnSpacing = 8;
			_panelStatistics.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_panelStatistics.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_panelStatistics.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_panelStatistics.Left = -4;
			_panelStatistics.Id = "_panelStatistics";
			_panelStatistics.Widgets.Add(label4);
			_panelStatistics.Widgets.Add(label5);
			_panelStatistics.Widgets.Add(label6);
			_panelStatistics.Widgets.Add(label7);
			_panelStatistics.Widgets.Add(label8);
			_panelStatistics.Widgets.Add(label9);
			_panelStatistics.Widgets.Add(_labelFps);
			_panelStatistics.Widgets.Add(_labelEffectsSwitches);
			_panelStatistics.Widgets.Add(_labelDrawCalls);
			_panelStatistics.Widgets.Add(_labelVerticesDrawn);
			_panelStatistics.Widgets.Add(_labelPrimitivesDrawn);
			_panelStatistics.Widgets.Add(_labelPasses);

			_labelCameraPosition = new Label();
			_labelCameraPosition.Text = "Camera: 1, 1, 1";
			_labelCameraPosition.Left = 4;
			_labelCameraPosition.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_labelCameraPosition.Visible = false;
			_labelCameraPosition.Id = "_labelCameraPosition";

			var panel1 = new Panel();
			StackPanel.SetProportionType(panel1, Myra.Graphics2D.UI.ProportionType.Fill);
			panel1.Widgets.Add(_tabControlScenes);
			panel1.Widgets.Add(_panelStatistics);
			panel1.Widgets.Add(_labelCameraPosition);

			_panelScenes = new VerticalStackPanel();
			_panelScenes.Id = "_panelScenes";
			_panelScenes.Widgets.Add(horizontalStackPanel1);
			_panelScenes.Widgets.Add(panel1);

			var panel2 = new Panel();
			panel2.Widgets.Add(_panelScenes);

			_propertyGrid = new PropertyGrid();
			_propertyGrid.Id = "_propertyGrid";

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.ShowHorizontalScrollBar = false;
			StackPanel.SetProportionType(scrollViewer1, Myra.Graphics2D.UI.ProportionType.Fill);
			scrollViewer1.Content = _propertyGrid;

			var label10 = new Label();
			label10.Text = "Reset Materials";

			var button1 = new Button();
			button1.Content = label10;

			_panelPropertiesButtons = new HorizontalStackPanel();
			_panelPropertiesButtons.Id = "_panelPropertiesButtons";
			_panelPropertiesButtons.Widgets.Add(button1);

			_panelProperties = new VerticalStackPanel();
			_panelProperties.Id = "_panelProperties";
			StackPanel.SetProportionType(_panelProperties, Myra.Graphics2D.UI.ProportionType.Part);
			_panelProperties.Widgets.Add(scrollViewer1);
			_panelProperties.Widgets.Add(_panelPropertiesButtons);

			_rightPanel = new VerticalStackPanel();
			_rightPanel.Id = "_rightPanel";
			_rightPanel.Widgets.Add(_panelProperties);

			_topSplitPane = new HorizontalSplitPane();
			_topSplitPane.Id = "_topSplitPane";
			_topSplitPane.Widgets.Add(_leftSplitPane);
			_topSplitPane.Widgets.Add(panel2);
			_topSplitPane.Widgets.Add(_rightPanel);

			var panel3 = new Panel();
			StackPanel.SetProportionType(panel3, Myra.Graphics2D.UI.ProportionType.Fill);
			panel3.Widgets.Add(_topSplitPane);

			
			Id = "_mainPanel";
			Widgets.Add(horizontalMenu1);
			Widgets.Add(panel3);
		}

		
		public MenuItem _menuItemSaveCurrentItem;
		public MenuItem _menuItemSaveEverything;
		public MenuItem _menuItemReloadCurrentItem;
		public MenuItem _menuItemProjectReferences;
		public MenuItem _menuItemQuit;
		public MenuItem _menuItemGraphicsSettings;
		public MenuItem _menuItemRenderEnvironment;
		public MenuItem _menuItemDebugSettings;
		public MenuItem _menuItemAbout;
		public ScrollViewer _panelSceneExplorer;
		public ScrollViewer _panelSolution;
		public VerticalSplitPane _leftSplitPane;
		public ToggleButton _buttonGrid;
		public ToggleButton _buttonCameraPosition;
		public TabControl _tabControlScenes;
		public Label _labelFps;
		public Label _labelEffectsSwitches;
		public Label _labelDrawCalls;
		public Label _labelVerticesDrawn;
		public Label _labelPrimitivesDrawn;
		public Label _labelPasses;
		public Grid _panelStatistics;
		public Label _labelCameraPosition;
		public VerticalStackPanel _panelScenes;
		public PropertyGrid _propertyGrid;
		public HorizontalStackPanel _panelPropertiesButtons;
		public VerticalStackPanel _panelProperties;
		public VerticalStackPanel _rightPanel;
		public HorizontalSplitPane _topSplitPane;
	}
}
