/* Generated by MyraPad at 5/24/2026 2:40:20 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Nursia.Editor.UI
{
	partial class ProjectReferencesWindow: Window
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "../../Reference/Reference1.dll";

			var label2 = new Label();
			label2.Text = "../References/Reference2.dll";

			_listReferences = new ListView();
			_listReferences.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_listReferences.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_listReferences.Id = "_listReferences";
			StackPanel.SetProportionType(_listReferences, Myra.Graphics2D.UI.ProportionType.Fill);
			_listReferences.Widgets.Add(label1);
			_listReferences.Widgets.Add(label2);

			var label3 = new Label();
			label3.Text = "Add";

			_buttonAdd = new Button();
			_buttonAdd.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_buttonAdd.Id = "_buttonAdd";
			_buttonAdd.Content = label3;

			var label4 = new Label();
			label4.Text = "Remove";

			_buttonRemove = new Button();
			_buttonRemove.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_buttonRemove.Id = "_buttonRemove";
			_buttonRemove.Content = label4;

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 4;
			verticalStackPanel1.Width = 100;
			verticalStackPanel1.Widgets.Add(_buttonAdd);
			verticalStackPanel1.Widgets.Add(_buttonRemove);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_listReferences);
			horizontalStackPanel1.Widgets.Add(verticalStackPanel1);

			
			Title = "Project References";
			Left = 464;
			Top = 228;
			Width = 600;
			Height = 200;
			Content = horizontalStackPanel1;
		}

		
		public ListView _listReferences;
		public Button _buttonAdd;
		public Button _buttonRemove;
	}
}
