/* Generated by MyraPad at 10/30/2025 5:41:38 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Nursia.Editor.UI
{
	partial class TerrainEditorPanel: HorizontalStackPanel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Raise";

			var label2 = new Label();
			label2.Text = "Lower";

			_comboInstrument = new ComboView();
			_comboInstrument.Id = "_comboInstrument";
			_comboInstrument.Widgets.Add(label1);
			_comboInstrument.Widgets.Add(label2);

			var label3 = new Label();
			label3.Text = "Radius:";

			_sliderRadius = new HorizontalSlider();
			_sliderRadius.Maximum = 20;
			_sliderRadius.Width = 200;
			_sliderRadius.Id = "_sliderRadius";

			_labelRadius = new Label();
			_labelRadius.Text = "5";
			_labelRadius.Id = "_labelRadius";

			var label4 = new Label();
			label4.Text = "Power:";

			_sliderPower = new HorizontalSlider();
			_sliderPower.Maximum = 1;
			_sliderPower.Value = 0.1f;
			_sliderPower.Width = 200;
			_sliderPower.Id = "_sliderPower";

			_labelPower = new Label();
			_labelPower.Id = "_labelPower";

			_panelAdditionalWidgets = new Panel();
			_panelAdditionalWidgets.Id = "_panelAdditionalWidgets";

			
			Spacing = 8;
			Id = "_panel";
			Widgets.Add(_comboInstrument);
			Widgets.Add(label3);
			Widgets.Add(_sliderRadius);
			Widgets.Add(_labelRadius);
			Widgets.Add(label4);
			Widgets.Add(_sliderPower);
			Widgets.Add(_labelPower);
			Widgets.Add(_panelAdditionalWidgets);
		}

		
		public ComboView _comboInstrument;
		public HorizontalSlider _sliderRadius;
		public Label _labelRadius;
		public HorizontalSlider _sliderPower;
		public Label _labelPower;
		public Panel _panelAdditionalWidgets;
	}
}
