using AssetManagementBase;
using Microsoft.Xna.Framework;
using Newtonsoft.Json;
using Nursia.Attributes;
using Nursia.Materials;
using Nursia.Rendering;
using Nursia.Serialization;
using Nursia.Utilities;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;

namespace Nursia.SceneGraph.Landscape
{
	[EditorInfo("Base")]
	public class TerrainNode : SceneNode, IHasExternalAssets
	{
		private HeightField _heightfield;
		internal Vector3 _localScale;
		private Vector3 _terrainSize = new Vector3(1000, 500, 1000);
		private bool _dirty = true;
		private int _detailLevels = 3;
		private int _patchSize = 32;
		private float _verticalSkirtScale = 0.1f;
		private float _halfWidth, _halfHeight;
		private readonly List<TerrainPatchNode> _patches = new List<TerrainPatchNode>();

		/// <summary>
		/// Unique terrain id generated by the editor
		/// </summary>
		[Browsable(false)]
		public int EditorId { get; set; }

		[Category("Terrain")]
		[JsonIgnore]
		public HeightField HeightField
		{
			get => _heightfield;

			set
			{
				if (value == _heightfield)
				{
					return;
				}

				if (_heightfield != null)
				{
					_heightfield.HeightChanged -= OnHeightChanged;
				}

				_heightfield = value;

				if (_heightfield != null)
				{
					_heightfield.HeightChanged += OnHeightChanged;
				}

				UpdateSizes();
				InvalidateAll();
			}
		}

		[Category("Terrain")]
		[JsonIgnore]
		public string HeightFieldSize => HeightField != null ? $"{HeightField.Columns}x{HeightField.Rows}" : "null";

		[Category("Terrain")]
		[Browsable(false)]
		public string HeightFieldPath { get; set; }

		[Category("Terrain")]
		public Vector3 TerrainSize
		{
			get => _terrainSize;

			set
			{
				if (value.EpsilonEquals(_terrainSize))
				{
					return;
				}

				_terrainSize = value;

				UpdateSizes();
				InvalidateAll();
			}
		}

		[Category("Terrain")]
		public int DetailLevels
		{
			get => _detailLevels;

			set
			{
				if (value == _detailLevels)
				{
					return;
				}

				_detailLevels = value;
				InvalidateAll();
			}
		}

		[Category("Terrain")]
		public int PatchSize
		{
			get => _patchSize;

			set
			{
				if (value == _patchSize)
				{
					return;
				}

				_patchSize = value;
				InvalidateAll();
			}
		}

		[Category("Terrain")]
		public float VerticalSkirtScale
		{
			get => _verticalSkirtScale;

			set
			{
				if (value.EpsilonEquals(_verticalSkirtScale))
				{
					return;
				}

				_verticalSkirtScale = value;
				InvalidateAll();
			}
		}

		public IMaterial Material { get; set; } = new TerrainMaterial();

		private bool Dirty
		{
			get => _dirty;

			set
			{
				if (value == _dirty)
				{
					return;
				}

				_dirty = value;
				Invalid?.Invoke(this, EventArgs.Empty);
			}
		}

		internal IReadOnlyList<TerrainPatchNode> Patches
		{
			get
			{
				Update();

				return _patches;
			}
		}

		public event EventHandler Invalid;

		public override void Load(AssetManager assetManager)
		{
			base.Load(assetManager);

			if (!string.IsNullOrEmpty(HeightFieldPath))
			{
				HeightField heightField;
				using (var stream = assetManager.Open(HeightFieldPath))
				{
					heightField = HeightField.FromStreamHf(stream);
				}

				HeightField = heightField;
			}

			var hasExternalAssets = Material as IHasExternalAssets;
			if (hasExternalAssets != null)
			{
				hasExternalAssets.Load(assetManager);
			}
		}

		protected override SceneNode CreateInstanceCore() => new TerrainNode();

		protected override void CopyFrom(SceneNode node)
		{
			base.CopyFrom(node);

			var terrainNode = (TerrainNode)node;

			HeightField = terrainNode.HeightField;
			HeightFieldPath = terrainNode.HeightFieldPath;
			TerrainSize = terrainNode.TerrainSize;
			DetailLevels = terrainNode.DetailLevels;
			PatchSize = terrainNode.PatchSize;
			VerticalSkirtScale = terrainNode.VerticalSkirtScale;

			if (terrainNode.Material != null)
			{
				Material = terrainNode.Material.Clone();
			}
		}

		public float GetHeight(Vector3 worldPos)
		{
			// From world pos to model
			worldPos = Vector3.Transform(worldPos, InverseGlobalTransform);

			var pos = new Vector2(worldPos.X, worldPos.Z);
			var hfPos = WorldToHeightField(pos);

			return HeightField.CalculateInterpolatedHeight(hfPos.X, hfPos.Y) * _localScale.Y;
		}

		public Vector3 ComputeNormal(Vector2 worldPos)
		{
			// From world pos to model
			var pos = worldPos;
			pos = Vector2.Transform(pos, InverseGlobalTransform);

			var hfPos = WorldToHeightField(pos);

			return ComputeNormal((int)hfPos.X, (int)hfPos.Y, 1);
		}

		internal float ComputeHeight(int x, int z)
		{
			return HeightField.GetHeight(x, z) * _localScale.Y;
		}


		internal Vector3 ComputeNormal(int x, int z, int step)
		{
			var width = HeightField.Columns;
			var height = HeightField.Rows;

			var p2 = HeightFieldToWorld2D(x, z);

			var p = new Vector3(p2.X, ComputeHeight(x, z), p2.Y);

			var stepXScaled = step * _localScale.X;
			var stepZScaled = step * _localScale.Z;

			var w = p - new Vector3(x >= step ? p2.X - stepXScaled : p2.X, ComputeHeight(x >= step ? x - step : x, z), p2.Y);
			var e = p - new Vector3(x < width - step ? p2.X + stepXScaled : p2.X, ComputeHeight(x < width - step ? x + step : x, z), p2.Y);
			var s = p - new Vector3(p2.X, ComputeHeight(x, z >= step ? z - step : z), z >= step ? p2.Y - stepZScaled : p2.Y);
			var n = p - new Vector3(p2.X, ComputeHeight(x, z < height - step ? z + step : z), z < height - step ? p2.Y + stepZScaled : p2.Y);

			var n0 = Vector3.Cross(n, w);
			var n1 = Vector3.Cross(w, s);
			var n2 = Vector3.Cross(e, n);
			var n3 = Vector3.Cross(s, e);
			Vector3 normal = -(n0 + n1 + n2 + n3);

			normal.Normalize();

			return normal;
		}

		internal Vector3 ComputeNormal(int x, int z) => ComputeNormal(x, z, 1);

		public Vector2 WorldToHeightField(Vector2 pos)
		{
			var result = new Vector2((pos.X / _localScale.X) + _halfWidth, (pos.Y / _localScale.Z) + _halfHeight);

			result.X = MathHelper.Clamp(result.X, 0, HeightField.Columns - 1);
			result.Y = MathHelper.Clamp(result.Y, 0, HeightField.Rows - 1);

			return result;
		}

		internal Vector2 HeightFieldToWorld2D(float x, float z)
		{
			return new Vector2((x - _halfWidth) * _localScale.X, (z - _halfHeight) * _localScale.Z);
		}


		public Vector3 HeightFieldToWorld(float x, float z)
		{
			var pos = HeightFieldToWorld2D(x, z);
			var height = HeightField.CalculateInterpolatedHeight(x, z) * _localScale.Y;

			return new Vector3(pos.X, height, pos.Y);
		}

		public Vector2 WorldToWeightMapNormalized(Vector2 pos)
		{
			var result = new Vector2(((pos.X / _localScale.X) + _halfWidth) / HeightField.Columns, 1.0f - ((pos.Y / _localScale.Z) + _halfHeight) / HeightField.Rows);

			result.X = MathHelper.Clamp(result.X, 0.0f, 1.0f);
			result.Y = MathHelper.Clamp(result.Y, 0.0f, 1.0f);

			return result;
		}

		public Vector2 WeightMapNormalizedToWorld(float x, float z)
		{
			return new Vector2((x * HeightField.Columns - _halfWidth) * _localScale.X, ((1.0f - z) * HeightField.Rows - _halfHeight) * _localScale.Z);
		}

		private void OnHeightChanged(Point pos)
		{
			if (_patches == null)
			{
				return;
			}

			// We can't use PatchesColumns/PatchesRows here, since they call Update
			foreach (var patch in _patches)
			{
				if (patch.PositionAffectsPatch(pos.X, pos.Y))
				{
					patch.Invalidate();
				}
			}
		}

		private void UpdateSizes()
		{
			if (HeightField == null)
			{
				return;
			}

			var width = HeightField.Columns;
			var height = HeightField.Rows;

			// Compute terrain scale
			_localScale = new Vector3(TerrainSize.X / (width - 1), TerrainSize.Y, TerrainSize.Z / (height - 1));

			_halfWidth = (width - 1) * 0.5f;
			_halfHeight = (height - 1) * 0.5f;
		}

		public override void AddRenderJobs(Camera camera, IRenderJobsBatch batch)
		{
			base.AddRenderJobs(camera, batch);

			Update();
		}

		private void Update()
		{
			if (!_dirty)
			{
				return;
			}

			// Rebuild everything
			_patches.Clear();
			if (HeightField != null)
			{
				UpdateSizes();

				var width = HeightField.Columns;
				var height = HeightField.Rows;

				var columns = width / PatchSize;
				var rows = height / PatchSize;

				// Compute the maximum step size, which is a function of our lowest level of detail.
				// This determines how many vertices will be skipped per triange/quad on the lowest
				// level detail terrain patch.
				int maxStep = (int)Math.Pow(2.0, DetailLevels - 1);

				// Create terrain patches
				for (var row = 0; row < rows; ++row)
				{
					for (var col = 0; col < columns; ++col)
					{
						var x1 = col * PatchSize;
						var x2 = Math.Min(x1 + PatchSize, width - 1);

						var z1 = row * PatchSize;
						var z2 = Math.Min(z1 + PatchSize, height - 1);

						// Create this patch
						var patch = new TerrainPatchNode(this, x1, z1, x2, z2, maxStep);

						_patches.Add(patch);
					}
				}
			}

			_dirty = false;
		}

		private void InvalidateAll()
		{
			_dirty = true;
			InvalidateActualChildren();
		}

		protected override IEnumerable<SceneNode> GetCustomChildren() => Patches;

		private bool IsAboveTerrain(Vector3 worldPos)
		{
			// From world pos to model
			var pos = Vector3.Transform(worldPos, InverseGlobalTransform);

			// Now y is supposed to be the point height
			return pos.Y > GetHeight(worldPos);
		}

		public Vector3? FindPosition(Ray ray)
		{
			if (FullBoundingBox == null)
			{
				return null;
			}

			var bb = FullBoundingBox.Value;
			var pos = ray.Position;
			if (bb.Contains(ray.Position) != ContainmentType.Contains)
			{
				// The ray starts outside of the box
				var dist = bb.Intersects(ray);
				if (dist == null)
				{
					// The ray doesn't intersects the box at all
					return null;
				}

				// Move pos to the entry intersection point
				pos = ray.Position + ray.Direction * dist.Value;
			}

			if (!IsAboveTerrain(pos))
			{
				// The entry point is below terrain, hence it is the result
				return pos;
			}

			var steps = 0;
			Vector3? result = null;
			while (steps < 50000)
			{
				// Check if we still inside
				var dist = bb.Intersects(new Ray(pos, ray.Direction));
				if (dist == null)
				{
					break;
				}

				// 2.0 is the step size
				var newPos = pos + ray.Direction * 2.0f;

				// We end the search here
				if (!IsAboveTerrain(newPos))
				{
					// Found
					result = (pos + newPos) / 2;
					break;
				}

				pos = newPos;
				++steps;
			}

			Debug.WriteLine($"TerrainNode.FindPosition Steps: {steps}");

			return result;
		}
	}
}
